### ISSUE TITLE
gst_device_to_shm Not Working

### ISSUE THREAD

**Issue by openedhardware** [mad4ms/python-opencv-gstreamer-examples#4]
I have tested [gst_device_to_shm.py](https://github.com/mad4ms/python-opencv-gstreamer-examples/blob/master/gst_device_to_shm.py) on Ubuntu 20.04, but `/tmp/foo` file is not created at all.

I can display the live video frame with `cv2.imshow()` command.

Any idea why it doesn't work?

Cheers.

**Comment by mad4ms** [comment]
I just tested it again and after setting correct camera parameters, the shared memory is created.

Since you can see the video feed with `cv2.imshow()`, it's unlikely that the camera is the issue.

Following ideas:

- Reassure that you have gstreamer compiled into opencv
- Check if the permissions of `/tmp` are set to 1777, which `ls` shows as `drwxrwxrwt`
- set export `GST_DEBUG=3` or `GST_DEBUG=4` before executing the python script and search for errors in the gstreamer logs.

Hope this helps. Best.
